"""
Phase 11 -- Explainability.

SHAP for the sole Phase 8 model this pipeline explains:
  - Isolation Forest (Model 1): shap.TreeExplainer -- exact, no background
    sample needed, fast at this scale.

Note: this file previously (pre deep-learning removal) also ran
shap.GradientExplainer on the Autoencoder (Model 9) and produced a
cross-model SHAP comparison (shap_global_importance_comparison.csv, the
IF-vs-AE rank-agreement scatter, and dual-panel local waterfalls). The
Autoencoder was removed from this pipeline -- see the project decision log --
and no other remaining classical model (LOF, OCSVM, Elliptic Envelope,
DBSCAN, HDBSCAN, K-Means, GMM) is naturally SHAP-compatible without an
expensive, unused KernelExplainer, so the cross-model comparison was dropped
entirely rather than swapped to a different second model. Isolation Forest
SHAP is now the sole explainability output.

Sign convention, checked empirically (not assumed) before use:
  - shap.TreeExplainer on sklearn's IsolationForest explains a quantity that
    is a monotonic transform of `score_samples`, the OPPOSITE convention from
    this project's `score_isolation_forest = -decision_function` (higher =
    more anomalous). So raw TreeExplainer shap values are NEGATED before use
    here, so that a positive shap value means "pushes the anomaly score up."

Outputs: artifacts_research/{shap_isolation_forest.csv,
shap_local_explanations.json}.
Plots: research/plots/{shap_global_importance_if.png,
shap_local_waterfall_<TransactionID>.png}.
"""
import json
import os
import sys
import time

import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import shap
from scipy.stats import spearmanr
from sklearn.model_selection import train_test_split

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config_research import ARTIFACTS_RESEARCH_DIR, PLOTS_DIR, RANDOM_STATE, ROOT_DIR

sns.set_style("whitegrid")
plt.rcParams.update({
    "figure.dpi": 110, "savefig.dpi": 110, "font.size": 10,
    "axes.titlesize": 12, "axes.titleweight": "bold", "axes.labelsize": 10,
})

FEATURES_V2_CSV = os.path.join(ARTIFACTS_RESEARCH_DIR, "features_v2.csv")
MODELS_DIR = os.path.join(ARTIFACTS_RESEARCH_DIR, "models")
ID_COLS = ["TransactionID", "AccountID"]

# Transactions to explain locally: derived from Phase 10's business-evaluation
# top-1%/top-10% tiers (regenerated by 10_evaluation.py, which runs before
# this script in the pipeline's execution order) rather than a hardcoded list,
# so this stays correct after any re-run.
BUSINESS_EVAL_JSON = os.path.join(ARTIFACTS_RESEARCH_DIR, "business_evaluation_examples.json")


def savefig(fig, name):
    path = os.path.join(PLOTS_DIR, name)
    fig.tight_layout()
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved plot: {path}")
    return path


def load_everything():
    df = pd.read_csv(FEATURES_V2_CSV)
    feature_cols = [c for c in df.columns if c not in ID_COLS]
    X = df[feature_cols].astype(float).values
    idx_train, idx_val = train_test_split(np.arange(len(df)), test_size=0.2, random_state=RANDOM_STATE)
    scaler = joblib.load(os.path.join(MODELS_DIR, "shared_robust_scaler.pkl"))
    X_train = scaler.transform(X[idx_train])
    X_all = scaler.transform(X)
    return df, feature_cols, X_all, X_train, idx_train


# --------------------------------------------------------- SHAP: Isolation Forest
def shap_isolation_forest(df, feature_cols, X_all):
    clf = joblib.load(os.path.join(MODELS_DIR, "isolation_forest.pkl"))
    t0 = time.time()
    explainer = shap.TreeExplainer(clf)
    raw_shap = explainer.shap_values(X_all.astype(np.float64))
    elapsed = time.time() - t0
    print(f"  TreeExplainer on Isolation Forest: {elapsed:.1f}s for {len(X_all)} rows")

    # Sign check: verify TreeExplainer's raw output tracks score_samples
    # (higher = more normal), the opposite of score_isolation_forest -- negate.
    raw_pred = clf.score_samples(X_all[:200])
    rho_check, _ = spearmanr(np.array(raw_shap[:200]).sum(axis=1), raw_pred)
    print(f"  Sign-check: Spearman(raw shap row-sums, score_samples) on 200-row spot-check = {rho_check:.4f} "
          f"(expect strongly positive -> negate to match anomaly-score-up convention)")
    anomaly_shap = -raw_shap

    out = pd.DataFrame(anomaly_shap, columns=feature_cols)
    out.insert(0, "TransactionID", df["TransactionID"].values)
    out.to_csv(os.path.join(ARTIFACTS_RESEARCH_DIR, "shap_isolation_forest.csv"), index=False)
    print(f"Saved: {os.path.join(ARTIFACTS_RESEARCH_DIR, 'shap_isolation_forest.csv')}")
    return anomaly_shap


# ----------------------------------------------------------------- Global importance
def global_importance(feature_cols, shap_if):
    mean_abs_if = np.abs(shap_if).mean(axis=0)

    comp = pd.DataFrame({
        "feature": feature_cols,
        "mean_abs_shap_isolation_forest": mean_abs_if,
    })
    comp["rank_isolation_forest"] = comp["mean_abs_shap_isolation_forest"].rank(ascending=False).astype(int)
    comp = comp.sort_values("rank_isolation_forest")

    top15 = comp.nlargest(min(15, len(comp)), "mean_abs_shap_isolation_forest").sort_values(
        "mean_abs_shap_isolation_forest")
    fig, ax = plt.subplots(figsize=(8, 6.5))
    ax.barh(top15["feature"], top15["mean_abs_shap_isolation_forest"], color="#2F6690")
    ax.set_xlabel("Mean |SHAP value| (anomaly-score-oriented, higher = more anomalous)")
    ax.set_title(f"Global Feature Importance (46 features) -- Isolation Forest\n"
                 f"(SHAP, TreeExplainer, n={len(comp)} features)")
    savefig(fig, "shap_global_importance_if.png")

    print("  Top-10 features by mean|SHAP| (Isolation Forest):")
    for _, r in comp.head(10).iterrows():
        print(f"    {r['feature']:35s} mean|SHAP|={r['mean_abs_shap_isolation_forest']:.5f}")

    return comp


# --------------------------------------------------------------- Local explanations
def pick_local_explain_ids():
    if os.path.exists(BUSINESS_EVAL_JSON):
        with open(BUSINESS_EVAL_JSON) as f:
            be = json.load(f)
        top1 = be["tiers"]["top_1pct"]["transaction_ids"]
        # top of the top-1% tier, plus one from deeper in it, plus the weakest
        # end of the top-10% tier -- a mix of "clear" and "does-not-look-like
        # -fraud" examples, matching this phase's prior local-explanation mix.
        ids = top1[:2]
        if len(top1) > 4:
            ids.append(top1[4])
        tail = be["tiers"].get("top_10pct", {}).get("transaction_ids", [])
        if tail:
            ids.append(tail[-1])
        return ids
    return []


def local_explanations(df, feature_cols, shap_if, explain_ids):
    results = {}
    for txn_id in explain_ids:
        matches = np.where(df["TransactionID"].values == txn_id)[0]
        if len(matches) == 0:
            continue
        i = matches[0]

        row_raw = df.iloc[i][feature_cols]
        if_vals = shap_if[i]

        if_top = pd.Series(if_vals, index=feature_cols).sort_values(key=np.abs, ascending=False).head(8)

        results[txn_id] = {
            "AccountID": str(df.iloc[i]["AccountID"]),
            "isolation_forest": {
                "top_contributors": [
                    {"feature": f, "shap_value": round(float(v), 5),
                     "raw_feature_value": round(float(row_raw[f]), 4),
                     "direction": "pushes score UP (more anomalous)" if v > 0 else "pushes score DOWN (more normal)"}
                    for f, v in if_top.items()
                ],
            },
        }

        fig, ax = plt.subplots(figsize=(7, 5.5))
        top_sorted = if_top.sort_values()
        colors = ["#D1495B" if v > 0 else "#2F6690" for v in top_sorted.values]
        ax.barh(top_sorted.index, top_sorted.values, color=colors)
        ax.axvline(0, color="black", lw=0.8)
        ax.set_title(f"Isolation Forest -- {txn_id}")
        ax.set_xlabel("SHAP contribution (+ = more anomalous)")
        fig.suptitle(f"Local SHAP Explanation -- {txn_id} (AccountID {df.iloc[i]['AccountID']})", fontsize=12)
        savefig(fig, f"shap_local_waterfall_{txn_id}.png")

    with open(os.path.join(ARTIFACTS_RESEARCH_DIR, "shap_local_explanations.json"), "w") as f:
        json.dump(results, f, indent=2, default=float)
    print(f"Saved: {os.path.join(ARTIFACTS_RESEARCH_DIR, 'shap_local_explanations.json')}")
    return results


def main():
    print("=== Phase 11: Explainability ===")
    df, feature_cols, X_all, X_train, idx_train = load_everything()

    print("\n--- SHAP: Isolation Forest (TreeExplainer) ---")
    shap_if = shap_isolation_forest(df, feature_cols, X_all)

    print("\n--- Global feature importance ---")
    comp = global_importance(feature_cols, shap_if)

    print("\n--- Local explanations ---")
    explain_ids = pick_local_explain_ids()
    print(f"  Transactions selected for local explanation: {explain_ids}")
    local = local_explanations(df, feature_cols, shap_if, explain_ids)

    print("\nPhase 11 complete.")


if __name__ == "__main__":
    main()
